### ISSUE TITLE
Development bug

### ISSUE THREAD

**Issue by Mineablechn** [Sirttas/ElementalCraft#126]
**Describe the bug**
I don't know what the bug is, here's the log:
Mixin apply failed elementalcraft.mixins.json:MixinPlayerEntity -> net.minecraft.entity.player.PlayerEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyVariable annotation on attackTargetEntityWithCurrentItemSetFlag3 could not find any targets matching 'Lnet/minecraft/entity/player/PlayerEntity;func_71059_n(Lnet/minecraft/entity/Entity;)V' in net.minecraft.entity.player.PlayerEntity. Using refmap elementalcraft.refmap.json [PREINJECT Applicator Phase -> elementalcraft.mixins.json:MixinPlayerEntity -> Prepare Injections ->  -> localvar$zzf000$attackTargetEntityWithCurrentItemSetFlag3(Z)Z -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyVariable annotation on attackTargetEntityWithCurrentItemSetFlag3 could not find any targets matching 'Lnet/minecraft/entity/player/PlayerEntity;func_71059_n(Lnet/minecraft/entity/Entity;)V' in net.minecraft.entity.player.PlayerEntity. Using refmap elementalcraft.refmap.json [PREINJECT Applicator Phase -> elementalcraft.mixins.json:MixinPlayerEntity -> Prepare Injections ->  -> localvar$zzf000$attackTargetEntityWithCurrentItemSetFlag3(Z)Z -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo.<init>(ModifyVariableInjectionInfo.java:45) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_271] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_271] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271] {}
	at net.minecraft.client.main.Main.main(Main.java:118) ~[forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52) ~[forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:108) [forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {}

**To Reproduce**
1. Download it from maven:https://modmaven.dev/sirttas/elementalcraft/ElementalCraft/1.16.5-2.7.9/ and the newest version of DPAnvil by implement fg.deobf()
2. Run them in IDEA
3. See the bug
**Expected behavior**
Run normally.

**Comment by Sirttas** [comment]
have you set the `mixin.env.refMapRemappingFile` property in your gradle? https://github.com/Sirttas/ElementalCraft/blob/b2e8bc9fc3051e5fa5217c4bb21c95fa964a1e07/build.gradle#L91

**Comment by Mineablechn** [comment]
Emm, I set it just now, but I still can't run Minecraft, It still crash. and the logs are the same.
Note: I don't use the shendai repository!
Does it cause by these:
def modmaven_user = System.getenv("MODMAVEN_USER") ?: project.findProperty("modmaven_user")
def modmaven_password = System.getenv("MODMAVEN_PASSWORD") ?: project.findProperty("modmaven_password")
def use_modmaven = modmaven_user != null && modmaven_password != null
def shendai_reposlite_user = System.getenv("SHENDAI_REPOSLITE_USER") ?: project.findProperty("shendai_reposlite_user")
def shendai_reposlite_password = System.getenv("SHENDAI_REPOSLITE_PASSWORD") ?: project.findProperty("shendai_reposlite_password")
def use_shendai_reposlite = shendai_reposlite_user != null && shendai_reposlite_password != null

**Comment by Sirttas** [comment]
It is completely unrelated.

**Comment by Sirttas** [comment]
After adding this line you need to rerun the run setup task.

> have you set the `mixin.env.refMapRemappingFile` property in your gradle?
> 
> https://github.com/Sirttas/ElementalCraft/blob/b2e8bc9fc3051e5fa5217c4bb21c95fa964a1e07/build.gradle#L91

**Comment by Mineablechn** [comment]
> After adding this line you need to rerun the run setup task.
> 
> > have you set the `mixin.env.refMapRemappingFile` property in your gradle?
> > https://github.com/Sirttas/ElementalCraft/blob/b2e8bc9fc3051e5fa5217c4bb21c95fa964a1e07/build.gradle#L91

I have rerun it, but it still crashed.

**Comment by Sirttas** [comment]
I just saw you were using an old version please use 2.7.17

**Comment by Mineablechn** [comment]
> I just saw you were using an old version please use 2.7.17

It still crashes after I use the newest mod. Also, there's a link to build.gradle: https://github.com/Mineablechn/Tinker-s-Revolution/blob/main/build.gradle

**Comment by Sirttas** [comment]
I had problems uploading to modmaven a som point try adding elemental craft repo: 
```groovy
maven {
    url "https://repo.elementalcraft.org/public"
}
```

**Comment by Mineablechn** [comment]
> I had problems uploading to modmaven a som point try adding elemental craft repo:
> 
> ```groovy
> maven {
>     url "https://repo.elementalcraft.org/public"
> }
> ```

But there is a problem that this maven doesn't have a version of elementalcraft in 1.16.5

**Comment by Sirttas** [comment]
I won't maintain 1.16 anymore. Please move to a more recent version.
