### ISSUE TITLE
Non-crashing warning / error related to JEI and colours

### ISSUE THREAD

**Issue by MaxWasUnavailable** [Sirttas/ElementalCraft#134]
**Describe the bug**
There seems to be an error thrown by JEI when checking some ElementalCraft items in JEI. It seems to be related to colours?

**To Reproduce**
1. Scroll through JEI and hover over some random ElementalCraft items.

**Expected behavior**
No errors.

**Relevant error**
```
java.lang.NoClassDefFoundError: mezz/jei/color/ColorGetter
	at sirttas.elementalcraft.item.ECItem.lookupColor(ECItem.java:62) ~[elementalcraft-1.18.2-4.4.28.jar%23198!/:1.18.2-4.4.28]
	at sirttas.elementalcraft.pureore.PureOreManager$Entry.getColor(PureOreManager.java:226) ~[elementalcraft-1.18.2-4.4.28.jar%23198!/:1.18.2-4.4.28]
	at sirttas.elementalcraft.pureore.PureOreManager.getColor(PureOreManager.java:97) ~[elementalcraft-1.18.2-4.4.28.jar%23198!/:1.18.2-4.4.28]
	at sirttas.elementalcraft.item.ECItems.lambda$registerItemColors$2(ECItems.java:352) ~[elementalcraft-1.18.2-4.4.28.jar%23198!/:1.18.2-4.4.28]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115162_(ItemRenderer.java:2087) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115189_(ItemRenderer.java:2057) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:156) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115127_(ItemRenderer.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174235_(ItemRenderer.java:299) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174277_(ItemRenderer.java:290) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115218_(ItemRenderer.java:282) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at mezz.jei.common.render.ItemStackRenderer.render(ItemStackRenderer.java:41) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.common.render.ItemStackRenderer.render(ItemStackRenderer.java:25) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.common.render.IngredientListRenderer.renderIngredient(IngredientListRenderer.java:118) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.common.render.IngredientListRenderer.renderIngredientType(IngredientListRenderer.java:98) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.common.render.IngredientListRenderer.render(IngredientListRenderer.java:88) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.common.gui.overlay.IngredientGrid.draw(IngredientGrid.java:143) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.common.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:184) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.common.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:188) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.common.gui.GuiEventHandler.onDrawBackgroundPost(GuiEventHandler.java:60) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.forge.startup.EventRegistration.lambda$registerGuiHandler$12(EventRegistration.java:103) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at mezz.jei.core.util.WeakConsumer.accept(WeakConsumer.java:17) ~[jei-1.18.2-forge-10.2.1.1004.jar%23286!/:10.2.1.1004]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96558_(Screen.java:450) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.gui.screens.Screen.m_7333_(Screen.java:444) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6305_(CreativeModeInventoryScreen.java:604) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403) ~[forge-1.18.2-40.2.1-universal.jar%23507!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[forge-1.18.2-40.2.1-universal.jar%23507!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23502!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.1.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.ClassNotFoundException: mezz.jei.color.ColorGetter
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 48 more
```

**Comment by Sirttas** [comment]
Fixed in 5.6.0
