### ISSUE TITLE
Latest EC version still crashes, broken world gen code [1.18.1]

### ISSUE THREAD

**Issue by itsdinkd** [Sirttas/ElementalCraft#68]
On a server instance, still cannot load EC.

```java
[01:34:38] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception initializing level
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:374) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:313) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:175) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:644) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Tried to biome check an unregistered feature
        at net.minecraft.world.level.levelgen.placement.BiomeFilter.m_191567_(BiomeFilter.java:27) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.placement.BiomeFilter.m_183168_(BiomeFilter.java:27) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at net.minecraft.world.level.levelgen.placement.PlacementFilter.m_183381_(PlacementFilter.java:11) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191801_(PlacedFeature.java:50) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191782_(PlacedFeature.java:40) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at sirttas.elementalcraft.world.feature.ECFeatures.addSpawnSource(ECFeatures.java:206) ~[elementalcraft-1.18.1-4.1.2.jar%23125!:1.18.1-4.1.2]
        at sirttas.elementalcraft.world.feature.ECFeatures.addSpawnSources(ECFeatures.java:194) ~[elementalcraft-1.18.1-4.1.2.jar%23125!:1.18.1-4.1.2]
        at net.minecraft.server.MinecraftServer.handler$zcm000$addSpawnSources(MinecraftServer.java:2869) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:361) ~[server-1.18.1-20211210.034407-srg.jar%23322!:?]
        ... 5 more
Exception in thread "Thread-5" java.lang.NullPointerException: Cannot invoke "java.lang.Thread.interrupt()" because "this.thread" is null
        at TRANSFORMER/simplerpc@1.18-version/me.hypherionmc.simplerpclib.util.FileWatcherService.stop(FileWatcherService.java:69)
        at java.base/java.lang.Thread.run(Thread.java:833)
        ```

**Comment by Sirttas** [comment]
fixed in 4.1.3
