### ISSUE TITLE
[1.18.1-Crash] java.lang.IllegalArgumentException: bound must be positive > Exception generating new chunk. (On Server).

### ISSUE THREAD

**Issue by Gbergz** [Sirttas/ElementalCraft#73]
**Describe the bug**
When generating a new world on A SERVER within my modpack, errors are thrown. Seems to be coming from Elemental Craft.
"`java.lang.IllegalArgumentException: bound must be positive > Exception generating new chunk.`"
"`Error executing task on Chunk source main thread executor for minecraft:overworld`".

Note: Singleplayer is fine. Not on multiplayer though.

**To Reproduce**
1. Start a Server
2. Generate world.
3. Console gets spammed with errors like "bound must be positive" & "exception generating new chunk".
"`Error executing task on Chunk source main thread executor for minecraft:overworld`".
4. Crash.
5. Profit.

"```at sirttas.elementalcraft.world.feature.placement.SourcePlacement.getHeight(SourcePlacement.java:29) ~[elementalcraft-1.18.1-4.1.7.jar%23155!/:1.18.1-4.1.7]
	at sirttas.elementalcraft.world.feature.ECFeatures.addSpawnSource(ECFeatures.java:190) ~[elementalcraft-1.18.1-4.1.7.jar%23155!/:1.18.1-4.1.7]
	at sirttas.elementalcraft.world.feature.ECFeatures.addSpawnSources(ECFeatures.java:181) ~[elementalcraft-1.18.1-4.1.7.jar%23155!/:1.18.1-4.1.7]```"

**Expected behavior**
That a world can be generated without issues.

### Versions: 
Forge: 39.0.75
Elemental Craft: 4.1.7 | https://www.curseforge.com/minecraft/mc-mods/elemental-craft/files/3593428
DP Anvil: 3.2.0 | https://www.curseforge.com/minecraft/mc-mods/datapack-anvil/files/3569515

**Part of Logs**: 
https://gist.github.com/Gbergz/c1b6aa75e2c7d0d38e2dce823e940e09

**Full Logs**:
[latest.log](https://github.com/Sirttas/ElementalCraft/files/8054081/latest.log)

**Crash-Report**:
https://gist.github.com/Gbergz/8ab64d1efe507fb848e18022529b906b

**ModPack:**
TNP Limitless 5 v0.17.1 (server)
https://www.curseforge.com/minecraft/modpacks/tnp-limitless-5

**Comment by Gbergz** [comment]
After some digging, this issue still happens without Elemental Craft.. so no idea if this is even an issue at all. But you can take a look if you want. Close if not.

**Comment by Gbergz** [comment]
Not your issue, apologies. Closing!
