### ISSUE TITLE
Crash due to lack of associated owner object

### ISSUE THREAD

**Issue by Letoric** [Sirttas/ElementalCraft#8]
This is the latest build as of 5 minutes ago. 

←[m←[33m[16:29:23] [main/WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry EntityType: Override did not have an associated owner object. Name: elementalcraft:earthgolem Value: entity.minecraft.pig
←[m←[1;31m[16:29:23] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
        at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:597) ~[?:?] {re:classloading}
        at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:633) ~[?:?] {re:classloading}
        at net.minecraftforge.registries.GameData.freezeData(GameData.java:280) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:219) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:46) ~[?:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.3-34.1.25.jar:34.1] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.3-34.1.25.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.3-34.1.25.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.3-34.1.25.jar:?] {}
←[m

**Comment by Sirttas** [comment]
fixed in 2.3.16
