### ISSUE TITLE
[Crash] Ore Purifier Recipe Null - 1.18.2-4.3.5

### ISSUE THREAD

**Issue by fxate** [Sirttas/ElementalCraft#82]
Game crashes when attempting to purify ores if (_conjecture_) number of items is too few when delivered, either by hand or by hopper (because it sends one by one). Placing the correct number of items by hand works. Save will continue to chain crash upon loading.

Tested to be true with both Copper (needs 3) and Iron (needs 3). Ancient Debris works correctly because only one is needed for the purification process so hoppers do not cause an issue. Remedied the issue using NBTexplorer to clear Purifier Inventory.

````
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 05/05/2022, 22:08
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "sirttas.elementalcraft.recipe.instrument.io.IPurifierRecipe.matches(sirttas.elementalcraft.block.instrument.IInstrument)" because "recipe" is null
	at sirttas.elementalcraft.block.instrument.io.purifier.PurifierBlockEntity.lookupRecipe(PurifierBlockEntity.java:44) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading,pl:object_holder_definalize:A}
	at sirttas.elementalcraft.block.instrument.io.purifier.PurifierBlockEntity.lookupRecipe(PurifierBlockEntity.java:20) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading,pl:object_holder_definalize:A}
	at sirttas.elementalcraft.block.entity.AbstractECCraftingBlockEntity.isRecipeAvailable(AbstractECCraftingBlockEntity.java:30) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading}
	at sirttas.elementalcraft.block.instrument.AbstractInstrumentBlockEntity.makeProgress(AbstractInstrumentBlockEntity.java:87) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading}
	at sirttas.elementalcraft.block.instrument.AbstractInstrumentBlockEntity.tick(AbstractInstrumentBlockEntity.java:52) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading}
	at sirttas.elementalcraft.block.AbstractECEntityBlock.lambda$createUpdateTicker$2(AbstractECEntityBlock.java:83) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at sirttas.elementalcraft.block.instrument.io.purifier.PurifierBlockEntity.lookupRecipe(PurifierBlockEntity.java:44) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading,pl:object_holder_definalize:A}
	at sirttas.elementalcraft.block.instrument.io.purifier.PurifierBlockEntity.lookupRecipe(PurifierBlockEntity.java:20) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading,pl:object_holder_definalize:A}
	at sirttas.elementalcraft.block.entity.AbstractECCraftingBlockEntity.isRecipeAvailable(AbstractECCraftingBlockEntity.java:30) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading}
	at sirttas.elementalcraft.block.instrument.AbstractInstrumentBlockEntity.makeProgress(AbstractInstrumentBlockEntity.java:87) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading}
	at sirttas.elementalcraft.block.instrument.AbstractInstrumentBlockEntity.tick(AbstractInstrumentBlockEntity.java:52) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading}
	at sirttas.elementalcraft.block.AbstractECEntityBlock.lambda$createUpdateTicker$2(AbstractECEntityBlock.java:83) ~[elementalcraft-1.18.2-4.3.5.jar%2373!/:1.18.2-4.3.5] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: elementalcraft:purifier // sirttas.elementalcraft.block.instrument.io.purifier.PurifierBlockEntity
	Block: Block{elementalcraft:purifier}[facing=east,waterlogged=false]
	Block location: World: (-2055,65,730), Section: (at 9,1,10 in -129,4,45; chunk contains blocks -2064,-64,720 to -2049,319,735), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,-64,512 to -2049,319,1023)
	Block: Block{elementalcraft:purifier}[facing=east,waterlogged=false]
	Block location: World: (-2055,65,730), Section: (at 9,1,10 in -129,4,45; chunk contains blocks -2064,-64,720 to -2049,319,735), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,-64,512 to -2049,319,1023)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Fxate'/186, l='ServerLevel[New World]', x=-2051.79, y=63.00, z=733.11]]
	Chunk stats: 28442
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,84,0), Section: (at 0,4,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4168828 game time, 845369 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 152309 (now: false), thunder time: 22489 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4262610384 bytes (4065 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4.01
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b06
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1259
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26262.12
	Virtual memory used (MB): 24085.21
	Swap memory total (MB): 9948.58
	Swap memory used (MB): 1168.32
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseG1GC -Xmx8G -Xms8G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Fxate'/186, l='ServerLevel[New World]', x=-2051.79, y=63.00, z=733.11]]
	Data Packs: vanilla, mod:sereneseasons (incompatible), mod:badpackets (incompatible), mod:terrablender (incompatible), mod:biomesoplenty (incompatible), mod:architectury (incompatible), mod:lightoverlay (incompatible), mod:jei (incompatible), mod:botania (incompatible), mod:wthit (incompatible), mod:cloth_config (incompatible), mod:forge (incompatible), mod:goprone, mod:dpanvil (incompatible), mod:curios (incompatible), mod:patchouli (incompatible), mod:elementalcraft (incompatible), mod:selene (incompatible), mod:supplementaries (incompatible), mod:ortus, mod:malum (incompatible), mod:citadel (incompatible), mod:alexsmobs (incompatible), Supplementaries Virtual Resourcepack, mod:treeharvester, mod:gravestone (incompatible), mod:collective, mod:mekanismadditions, mod:ae2 (incompatible), mod:mekanism, mod:appbot (incompatible), mod:mekanismtools, mod:mekanismgenerators, mod:appmek (incompatible), mod:ambientsounds (incompatible), mod:creativecore (incompatible), mod:configured (incompatible), mod:catalogue (incompatible), mod:appleskin (incompatible), mod:domum_ornamentum (incompatible), mod:blockui (incompatible), mod:structurize (incompatible), mod:multipiston (incompatible), mod:minecolonies (incompatible), mod:journeymap
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 25
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 512.59
	OpenGlRenderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TerraBlender-forge-1.18.2-1.1.0.99.jar            |TerraBlender                  |terrablender                  |1.18.2-1.1.0.99     |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar          |Ambient Sounds                |ambientsounds                 |5.0.16              |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.109-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.109   |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.18.2-10.2.0.459.jar           |Mekanism: Additions           |mekanismadditions             |10.2.0              |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.9_mc1.18.2.jar            |CreativeCore                  |creativecore                  |2.6.9               |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.18.2-5.1.jar                      |Tree Harvester                |treeharvester                 |5.1                 |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-forge-10.0.0.191.jar                   |Just Enough Items             |jei                           |10.0.0.191          |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-11.0.0-alpha.6.jar            |Applied Energistics 2         |ae2                           |11.0.0-alpha.6      |DONE      |Manifest: NOSIGNATURE
		Botania-1.18.2-431.jar                            |Botania                       |botania                       |1.18.2-431          |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.2-1.0.50-ALPHA |DONE      |Manifest: NOSIGNATURE
		wthit-forge-4.9.0.jar                             |wthit                         |wthit                         |4.9.0               |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.18.2-10.2.0.459.jar                    |Mekanism                      |mekanism                      |10.2.0              |DONE      |Manifest: NOSIGNATURE
		dpanvil-1.18.2-3.3.2c.jar                         |DataPack Anvil                |dpanvil                       |1.18.2-3.3.2c       |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.0.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-67.jar                           |Patchouli                     |patchouli                     |1.18.2-67           |DONE      |Manifest: NOSIGNATURE
		elementalcraft-1.18.2-4.3.5.jar                   |ElementalCraft                |elementalcraft                |1.18.2-4.3.5        |DONE      |Manifest: NOSIGNATURE
		blockui-1.18.2-0.0.47-ALPHA.jar                   |UI Library Mod                |blockui                       |1.18.2-0.0.47-ALPHA |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.2.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-4.25.jar                        |Collective                    |collective                    |4.25                |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.2-5.8.3-forge.jar                 |Journeymap                    |journeymap                    |5.8.3               |DONE      |Manifest: NOSIGNATURE
		ortus-1.18.2-1.0.jar                              |Ortus Lib                     |ortus                         |1.18.2-1.0          |DONE      |Manifest: NOSIGNATURE
		malum-1.18.2-1.3.5.jar                            |Malum                         |malum                         |1.18.2-1.3.5        |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.2-1.18.2.jar                         |Citadel                       |citadel                       |1.11.2              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.17.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.17.5              |DONE      |Manifest: NOSIGNATURE
		Serene+Seasons-1.18.2-7.0.0.13.jar                |Serene Seasons                |sereneseasons                 |1.18.2-7.0.0.13     |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.2.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		badpackets-forge-0.1.1.jar                        |Bad Packets API               |badpackets                    |0.1.1               |DONE      |Manifest: NOSIGNATURE
		Applied-Botanics-1.0.1.jar                        |Applied Botanics              |appbot                        |1.0.1               |DONE      |Manifest: NOSIGNATURE
		structurize-1.18.2-1.0.389-RELEASE.jar            |Structurize                   |structurize                   |1.18.2-1.0.389-RELEA|DONE      |Manifest: NOSIGNATURE
		multi-piston-1.18.2-1.2.3-ALPHA.jar               |Multi-Piston                  |multipiston                   |1.18.2-1.2.3-ALPHA  |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.18.2-1.0.694-ALPHA.jar             |MineColonies                  |minecolonies                  |1.18.2-1.0.694-ALPHA|DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.18.2-10.2.0.459.jar               |Mekanism: Tools               |mekanismtools                 |10.2.0              |DONE      |Manifest: NOSIGNATURE
		architectury-4.2.50.jar                           |Architectury                  |architectury                  |4.2.50              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.18.2-10.2.0.459.jar          |Mekanism: Generators          |mekanismgenerators            |10.2.0              |DONE      |Manifest: NOSIGNATURE
		catalogue-1.6.1-1.18.2.jar                        |Catalogue                     |catalogue                     |1.6.1               |DONE      |Manifest: NOSIGNATURE
		light-overlay-6.0.5-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.5               |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.2.57-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.57              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.0-universal.jar                 |Forge                         |forge                         |40.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		goprone-1.18.2-1.7.0.jar                          |GoProne                       |goprone                       |1.18.2-1.7.0        |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		Applied-Mekanistics-1.1.5-beta.jar                |Applied Mekanistics           |appmek                        |1.1.5-beta          |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.15.6.jar                          |Selene                        |selene                        |1.18.2-1.15.6       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.3.7.jar                  |Supplementaries               |supplementaries               |1.18.2-1.3.7        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 11de5389-1490-4507-96e4-2efb460dcd59
	FML: 40.1
	Forge: net.minecraftforge:40.1.0
```

**Comment by Sirttas** [comment]
fixed in 4.3.6
